name: 'xport FoD vulnerability data to GitHub'
description: 'xport FoD vulnerability data to GitHub'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: fortify/github-action/setup@feat-2
      with:
        export-path: false
        vuln-exporter: action-default
    - run: |
        case ${SSC_APPVERSION} in
          ''|*[!0-9]*) echo '_APPVERSION_OPT="--ssc.version.name="'${SSC_APPVERSION}'"' >> $GITHUB_ENV ;;
          *) echo '_APPVERSION_OPT="--ssc.version.id=${SSC_APPVERSION}"' >> $GITHUB_ENV ;;
        esac
      shell: bash
    - uses: fortify/github-action/internal/run@feat-2
      with:
        cmd: '"${VULN_EXPORTER_CMD}" SSCToGitHub "--ssc.baseUrl=${SSC_URL}" "--ssc.user=${SSC_USER}" "--ssc.password=${SSC_PASSWORD}" "--ssc.authToken=${SSC_TOKEN}" "${_APPVERSION_OPT}"'
    - run: |
        echo '_APPVERSION_OPT=""' >> $GITHUB_ENV
      shell: bash
    # Uploaded the generated file containing Fortify vulnerabilities to GitHub.
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ./gh-fortify-sast.sarif

    # Optionally store the generated file for troubleshooting purposes.
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: sarif-files
        path: ./gh-fortify-sast.sarif

branding:
  icon: 'shield'
  color: 'blue'

