name: 'Run "fcli fod session login" command'
description: 'Run "fcli fod session login" command based on environment variables'
author: 'Fortify'
runs:
  using: composite
  steps:
    # TODO If we wait for scan completion, potentially we could generate a CIToken if 
    #      SSC_USER and SSC_PASSWORD have been set, and then revoke the token once the
    #      scan has been successfully processed on SSC.
    # Define login options
    - run: |
        if [ -z "$SSC_URL" ]; then
          echo "ERROR: SSC_URL environment variable must be set"; exit 1;
        fi
        if [ -z "$SC_SAST_TOKEN" ]; then
          echo "ERROR: SC_SAST_TOKEN environment variable must be set"; exit 1;
        fi
        if [ -z "SSC_TOKEN" ]; then
          echo "ERROR: SSC_TOKEN environment variable must be set"; exit 1;
        fi
        echo '_SC_SAST_LOGIN_OPTS=--ssc-url "${SSC_URL}" -t "${SSC_TOKEN}" -c "${SC_SAST_TOKEN}" ${EXTRA_SC_SAST_LOGIN_OPTS}' >> $GITHUB_ENV
      shell: bash
    # Run fcli login command; note that the calling action/workflow is responsible for installing fcli
    - uses: fortify/github-action/internal/run@v1.1.0
      with:
        cmd: '"${FCLI_CMD}" sc-sast session login ${_SC_SAST_LOGIN_OPTS}' 
    # Clean up temporary environment variables
    - run: |
        echo '_SC_SAST_LOGIN_OPTS=""' >> $GITHUB_ENV
      shell: bash              
branding:
  icon: 'shield'
  color: 'blue'

