name: 'Setup Fortify Tools'
description: 'Set up Fortify tools like fcli, ScanCentral Client, FoDUploader and FortifyVulnerabilityExporter'
author: 'Fortify'
inputs:
  export-path:
    description: 'Whether to add the installed tools to the system PATH variable. Allowed values: true (default) or false'
    default: 'true'
    required: false
  tool-definitions:
    description: 'Local or remote location of the Fortify yaml tool definitions zip-file. Default value: https://github.com/fortify/tool-definitions/releases/download/v1/tool-definitions.yaml.zip'
    required: false
  fcli:
    description: 'The ScanCentral Client version to install. Allowed values: `skip` (default value, do not install), `latest`, or specific version number. Supports semantic versioning, for example `23.1` will install the latest known `23.1.y` patch version. Version may be specified either with or without the `v` prefix, for example `v23.1` and `23.1` are semantically the same.'
    default: 'skip'
    required: false
  sc-client:
    description: 'The ScanCentral Client version to install. Allowed values: skip (default value, do not install), latest, or specific version number.'
    default: 'skip'
    required: false
  fod-uploader:
    description: 'The FoDUploader version to install. Allowed values: `skip` (default value, do not install), `latest`, or specific version number. Supports semantic versioning, for example `v5` will install the latest known `5.x.y` version. Version may be specified either with or without the `v` prefix, for example `v5.4.0` and `5.4.0` are semantically the same.'
    default: 'skip'
    required: false
  vuln-exporter:
    description: 'The FortifyVulnerabilityExporter version to install. Allowed values: `skip` (default value, do not install), `latest`, or specific version number. Supports semantic versioning, for example `v2` will install the latest known `2.x.y` version. Version may be specified either with or without the `v` prefix, for example `v2.0.4` and `2.0.4` are semantically the same.'
    default: 'skip'
    required: false
  bugtracker-utility:
    description: 'The FortifyBugTrackerUtility version to install. Allowed values: `skip` (default value, do not install), `latest`, or specific version number. Supports semantic versioning, for example `v4` will install the latest known `4.x` version. Version may be specified either with or without the `v` prefix, for example `v4.12` and `4.12` are semantically the same.'
    default: 'skip'
    required: false
  debricked-cli:
    description: 'The Debricked CLI version to install. Allowed values: `skip` (default value, do not install), `latest`, or specific version number. Supports semantic versioning, for example `v1` will install the latest known `1.x` version. Version may be specified either with or without the `v` prefix, for example `v1.7` and `1.7` are semantically the same.'
    default: 'skip'
    required: false  
runs:
  using: node20
  main: 'dist/index.js'
branding:
  icon: 'shield'
  color: 'blue'

