#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
./update-action-refs.sh "$(git rev-parse --abbrev-ref HEAD)"
(cd internal/run && NODE_OPTIONS=--openssl-legacy-provider npm run build && git add dist/)
(cd setup && NODE_OPTIONS=--openssl-legacy-provider npm run build && git add dist/)
